import {
  BookOpen,
  LayoutDashboard,
  Search,
  Settings,
  Wrench,
  Shield,
  LogOut,
  Smartphone,
  Monitor,
  Star,
  ExternalLink,
  MoreHorizontal,
  Bell,
  Eye,
  EyeOff,
  Clock,
  Flame,
  Crown,
  RefreshCw,
  Download,
  Upload,
  ArrowRight,
  BarChart3,
  CircleHelp,
  Bot,
  type LucideProps,
} from 'lucide-react';

export {
  BookOpen as BookOpenIcon,
  LayoutDashboard as DashboardIcon,
  Search as SearchIcon,
  Settings as GearIcon,
  Wrench as WrenchIcon,
  Shield as ShieldIcon,
  LogOut as LogOutIcon,
  Smartphone as SmartphoneIcon,
  Monitor as MonitorIcon,
  ExternalLink as ExternalLinkIcon,
  MoreHorizontal as MoreHorizIcon,
  Bell as BellIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Clock as ClockIcon,
  Flame as FlameIcon,
  Crown as CrownIcon,
  RefreshCw as RefreshIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  ArrowRight as ArrowRightIcon,
  BarChart3 as BarChartIcon,
  CircleHelp as HelpCircleIcon,
  Bot as BotIcon,
};

export function StarIcon({
  filled = false,
  ...props
}: LucideProps & { filled?: boolean }) {
  return <Star {...props} fill={filled ? 'currentColor' : 'none'} />;
}
